---
- set_fact:
    userid: "{{ inventory_hostname | regex_replace('[^0-9]', '') }}"

# ADD PROJECT 1.3
- name: ADD Ansible Workshop Project INTO TOWER
  tower_project:
    name: "Ansible Workshop Project"
    description: "Workshop playbooks"
    organization: Default
    scm_type: git
    scm_url: "https://gitlab.redhatgov.io/{{ user_prefix }}{{ userid }}/{{ user_prefix }}{{ userid }}.git"
    scm_credential: "Git Credential"
    scm_clean: false
    scm_delete_on_update: false
    scm_update_on_launch: true
    tower_username: admin
    tower_password: "{{ towerpass }}"
    tower_host: "s{{ userid }}-tower.{{ dns_domain_name }}"
    tower_verify_ssl: no

- name: sleep for 10 seconds for project to update and continue with play
  wait_for:
    timeout: 10

# CREATE IIS Basic Job Template 4.1
- name: CREATE IIS BASIC JOB IN TOWER
  tower_job_template:
    name: "IIS Basic Job Template"
    description: "Template for the iis-basic-playbook"
    job_type: "run"
    inventory: "Ansible Workshop Inventory"
    project: "Ansible Workshop Project"
    playbook: iis_basic/install_iis.yml
    credential: "Student Account"
    limit: "Windows"
    fact_caching_enabled: true
    survey_enabled: true
    survey_spec: "{{ lookup('template', 'survey1.json') }}"
    tower_username: admin
    tower_password: "{{ towerpass }}"
    tower_host: "s{{ userid }}-tower.{{ dns_domain_name }}"
    tower_verify_ssl: no

# CREATE IIS Advanced TEMPLATE 5.1
- name: CREATE IIS Advanced Template IN TOWER
  tower_job_template:
    name: "IIS Advanced"
    description: "Template for iis_advanced"
    job_type: "run"
    inventory: "Ansible Workshop Inventory"
    project: "Ansible Workshop Project"
    playbook: iis_advanced/site.yml
    credential: "Student Account"
    limit: "Windows"
    fact_caching_enabled: true
    survey_enabled: true
    survey_spec: "{{ lookup('template', 'survey2.json') }}"
    tower_username: admin
    tower_password: "{{ towerpass }}"
    tower_host: "s{{ userid }}-tower.{{ dns_domain_name }}"
    tower_verify_ssl: no

# CREATE IIS Advanced Role TEMPLATE 6.1
- name: CREATE IIS Advanced Role Template IN TOWER
  tower_job_template:
    name: "IIS Advanced Role"
    description: "Template for iis_advanced role"
    job_type: "run"
    inventory: "Ansible Workshop Inventory"
    project: "Ansible Workshop Project"
    playbook: iis_advanced_role/site.yml
    credential: "Student Account"
    limit: "Windows"
    fact_caching_enabled: true
    survey_enabled: true
    survey_spec: "{{ lookup('template', 'survey2.json') }}"
    tower_username: admin
    tower_password: "{{ towerpass }}"
    tower_host: "s{{ userid }}-tower.{{ dns_domain_name }}"
    tower_verify_ssl: no

# CREATE Windows Updates TEMPLATE 7.1
- name: CREATE Windows Updates Template IN TOWER
  tower_job_template:
    name: "Windows Updates"
    description: "Template for windows updates"
    job_type: "run"
    inventory: "Ansible Workshop Inventory"
    project: "Ansible Workshop Project"
    playbook: win_updates/site.yml
    credential: "Student Account"
    limit: "Windows"
    fact_caching_enabled: true
    survey_enabled: true
    survey_spec: "{{ lookup('template', 'survey3.json') }}"
    tower_username: admin
    tower_password: "{{ towerpass }}"
    tower_host: "s{{ userid }}-tower.{{ dns_domain_name }}"
    tower_verify_ssl: no